import = ["~/.config/alacritty/iceberg.toml"]

[font]
size = 16.0

[font.italic]
family = "Operator Mono"
style = "Book Italic"

[font.normal]
family = "Operator Mono"
style = "Book"

[font.bold]
family = "Operator Mono"
style = "Bold"

[font.bold_italic]
family = "Operator Mono"
style = "Bold Italic"

[window]
#opacity = 0.85
opacity = 0.999
dimensions = { columns = 150, lines = 40 }

[font.offset]
x = 0
y = 3

