" Enable syntax highlighting
syntax on

" Enable filetype detection
filetype plugin on

" Use Vim settings rather than Vi settings
set nocompatible

" Set dark background
set background=dark

" Indentation settings
set tabstop=4
set shiftwidth=4
set softtabstop=4
set autoindent
set smartindent
set cindent

" Show line numbers and relative line numbers
set number
set relativenumber

" Enable system clipboard integration
set clipboard=unnamed

" Define leader key as comma
let g:mapleader = ','

" Source color column toggle script
source ~/.vim/autoload/toggle_colorcolumn.vim

" Set the signcolumn in the number column
set signcolumn=number

" Set the update time for CursorHold events
set updatetime=300

"let g:airline_theme='gruvbox'

" Plugin manager setup (vim-plug)
call plug#begin('~/.vim/plugged')
  Plug 'sheerun/vim-polyglot'
  "Plug 'morhetz/gruvbox'
  Plug 'gruvbox-community/gruvbox'
  Plug 'neoclide/coc.nvim', {'branch': 'release'}
  Plug 'vim-airline/vim-airline'
  "Plug 'vim-airline/vim-airline-themes'
  Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
  Plug 'shirk/vim-gas'
  Plug 'github/copilot.vim'
  Plug 'fatih/vim-go', { 'do': ':GoInstallBinaries' }
  Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' }
  Plug 'preservim/nerdcommenter'
  Plug 'alvan/vim-closetag'
  Plug 'ayu-theme/ayu-vim'
  Plug 'matze/vim-move'
  Plug 'Yggdroot/indentLine'
  Plug 'bling/vim-bufferline'
  Plug 'chclouse/tiger-vim'
  Plug 'arcticicestudio/nord-vim'
call plug#end()

let g:move_key_modifier = 'C'
let g:move_key_modifier_visualmode = 'C'

" Gruvbox theme configuration
" Set gruvbox color scheme with hard contrast
let g:gruvbox_contrast_dark='hard'
"let g:gruvbox_number_column='bg1'
"let g:gruvbox_contrast_light="hard"
let g:gruvbox_italic='1'
colorscheme gruvbox

" Ayu theme configuration
"let ayucolor='light'
"colorscheme ayu

" Coc.nvim configuration
let g:coc_global_extensions = ['coc-pairs', 'coc-clangd', 'coc-go', 'coc-prettier']

" Use <CR> to trigger coc completion
"inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : \"\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm() : 
                                           \"\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" GoTo code navigation
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Highlight the symbol and its references when holding the cursor
autocmd CursorHold * silent call CocActionAsync('highlight')

" Apply the most preferred quickfix action to fix diagnostic on the current line
nmap <leader>qf  <Plug>(coc-fix-current)

" FZF mapping to open files with <leader>f
nnoremap <Leader>f :FZF<CR>

" Hexokinase configuration
"set termguicolors
let g:Hexokinase_highlighters = ['backgroundfull']
let g:Hexokinase_refreshEvents = ['TextChanged', 'InsertLeave', 'BufRead', 'TextChangedI']


" IndentLine configuration
" let g:indentLine_char = '▏'

" Only if the character is the first of the column
let g:indentLine_char = '⎸'

" Vim airline configuration

" Disable airline
" let g:airline#enabled = 0
let g:airline_disable_statusline = 1

" Enable bufferline and airline together
"let g:airline#extensions#bufferline#enabled = 1
"let g:airline#extensions#bufferline#overwrite_variables = 1

"let g:bufferline_echo = 0
"autocmd VimEnter *
  "\ let &statusline='%{bufferline#refresh_status()}'
    "\ .bufferline#get_status_string()

" Change  cursor shape in different modes
"autocmd VimEnter,InsertLeave * set guicursor=n-v-c:block-Cursor/lCursor


" -----------------------------------------------------------------------------
" General settings
" -----------------------------------------------------------------------------

" Use a line cursor within insert mode, block cursor everywhere else.
let &t_SI = "\e[5 q" " blinking vertical
let &t_EI = "\e[2 q" " blinking block

" -----------------------------------------------------------------------------
" Coc configuration
" -----------------------------------------------------------------------------

" Use K to show documentation in preview window
nnoremap <silent> K :call ShowDocumentation()<CR>
function! ShowDocumentation()
  if CocAction('hasProvider', 'hover')
    call CocActionAsync('doHover')
  else
    call feedkeys('K', 'in')
  endif
endfunction

"  Toggle inlay hints with <leader>h
nnoremap <leader>h :CocCommand document.toggleInlayHint<CR>

" -----------------------------------------------------------------------------
" Copilot configuration
" -----------------------------------------------------------------------------

" Enable Copilot by default.
" let g:copilot_enabled = 1

" Disable Copilot by default.
let g:copilot_enabled = 0

" Toggle Github Copilot with <leader>gc
nnoremap <leader>gc :call ToggleCopilot()<cr>
function! ToggleCopilot()
  if exists('g:copilot_enabled') && g:copilot_enabled
    let g:copilot_enabled = 0
    echo "Copilot disabled"
  else
    let g:copilot_enabled = 1
    echo "Copilot enabled"
  endif
endfunction

" -----------------------------------------------------------------------------
"set termguicolors
"colorscheme iceberg
"colorscheme gruvbox
"hi Normal guibg=NONE ctermbg=NONE
 "Highlight Comment, html and copilot suggestion in italics
hi Comment cterm=italic
hi htmlItalic cterm=italic
hi CopilotSuggestion cterm=italic

set rtp^="/Users/toutane/.opam/default/share/ocp-indent/vim"
