# Database configurations
export DB_USERNAME="toutane"
export PGDATA="$HOME/postgres_data"
export PGHOST="/tmp"

# Java configuration
export JAVA_HOME=$(/usr/libexec/java_home -v 17.0.5)

# Golang configuration
export GO111MODULE=on
export GOPATH=$HOME/go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOPATH/bin:$GOROOT/bin

# Deno configuration
export PATH="/Users/toutane/.deno/bin:$PATH"

# Path configurations
export PATH=/usr/local/bin:$PATH
export PATH=/Users/toutane/Library/Application\ Support/Coursier/bin/:$PATH

# Node Version Manager (NVM) configuration
export NVM_DIR="$HOME/.nvm"
[ -s "/usr/local/opt/nvm/nvm.sh" ] && \. "/usr/local/opt/nvm/nvm.sh"  # Load nvm
[ -s "/usr/local/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/usr/local/opt/nvm/etc/bash_completion.d/nvm"  # Load nvm bash_completion

# Rust configurations
. "$HOME/.cargo/env"

# LLVM configurations
export PATH="/usr/local/opt/llvm/bin:$PATH"

# Bat configurations
export BAT_THEME="gruvbox-dark"

# Tmux configurations
export TERM="xterm-256color"

DEFAULT_SESSION_NAME="default"

# Set up tmux if it's not already running
if ! tmux has-session -t $DEFAULT_SESSION_NAME 2> /dev/null ; then
  # Create a new session
  tmux new-session -s $DEFAULT_SESSION_NAME
else
  # Check if we're already inside tmux
  if [ -z "$TMUX" ]; then
    tmux attach -t $DEFAULT_SESSION_NAME
  fi
fi

# Load zsh configurations
source ~/.dotfiles/zsh/aliases.sh
source ~/.dotfiles/zsh/git_prompt.sh

# Set up the prompt
bright_green="%F{10}"
precmd() PROMPT="${bright_green}%n@%m%f:%F{blue}%~%f$(git_prompt)$ "
